server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: urbankicks
  datasource:
    url: jdbc:mysql://localhost:3306/urbankicks2.0?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

cloudinary:
  cloud_name: dl6yzljsi
  api_key: 737337559354754
  api_secret: tTRK3wleDIy4Ai3dvUPcdHFskyY